/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QvYJbRfHjNr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function CVForm() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <CardTitle>Upload Your CV</CardTitle>
        <CardDescription>Fill out the form below to provide your CV information.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="phone">Phone</Label>
            <Input id="phone" placeholder="Enter your phone number" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="position">Current Position</Label>
            <Input id="position" placeholder="Enter your current position" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="experience">Work Experience</Label>
          <Textarea className="min-h-[100px]" id="experience" placeholder="Describe your work experience" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="education">Education</Label>
          <Textarea className="min-h-[100px]" id="education" placeholder="Describe your education" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="skills">Skills</Label>
          <Textarea className="min-h-[100px]" id="skills" placeholder="List your skills" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="resume">Resume</Label>
          <Input id="resume" type="file" />
        </div>
      </CardContent>
      <CardFooter>
        <Button type="submit">Submit CV</Button>
      </CardFooter>
    </Card>
  )
}
